### ISSUE TITLE
Ubuntu环境下 脚手架初始化项目失败

### ISSUE THREAD

**Issue by Hudiebbk** [SugarTurboS/Sugar-Electron#7]
`events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'clone',
    '--depth',
    '1',
    '--',
    'https://github.com/954053260/sugar-electron-vue-demo.git',
    '/home/huan/workspace/web/le/electron-le/suger-le/__download__'
  ]
}`

**Comment by 954053260** [comment]
从报错来看，脚手架使用下载模块代码的插件“download-git-repo”在Ubuntu环境出现问题。正在排查原因
